- Numpy(Numertical Puthon)
- Numpy => Vector와 Matrix연산에 강점
- ndarray => n-차원의 배열
- list와 거의 유사. 하지만 ndarray의 각 요소는 모두 같은 데이터 타입
- ndarray 생성하는 방법들
    - numpy.array([1,2,3])
    - numpy.arange()
    - numpy.ones(), zeros(), empty(), full()
- shpae, reshape() => view
---

- indexing, slicing
- 기본 indexingm boolean indexing, fancy indexing

In [7]:
import numpy as np

arr = np.arange(10, 20, 1)

# 열겨형(enumerate)을 사용하면 index와 원소를 함께 알 수 있다
for index, temp in enumerate(arr):
    print('인덱스 : {}, 값 : {}'.format(index, temp))

인덱스 : 0, 값 : 10
인덱스 : 1, 값 : 11
인덱스 : 2, 값 : 12
인덱스 : 3, 값 : 13
인덱스 : 4, 값 : 14
인덱스 : 5, 값 : 15
인덱스 : 6, 값 : 16
인덱스 : 7, 값 : 17
인덱스 : 8, 값 : 18
인덱스 : 9, 값 : 19


- ndarray의 sclicing도 python의 list와 동일한 형태로 사용

In [11]:
arr = np.arange(0, 5, 1)
print(arr[0:2])
print(arr[0:-1])
# 시작:끝:간격
print(arr[1:4:2])

[0 1]
[0 1 2 3]
[1 3]


In [17]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
# 2행 2열
print(arr[1,1])
# 2행의 전체
print(arr[1,:])
# 2행, 3행 전체
print(arr[1:3,:])
# 행만 명시 가능
print(arr[0])

6
[5 6 7 8]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]


- boolean indexing

In [21]:
np.random.seed(1)
arr = np.random.randint(1,20,(10,))
print(arr)

for temp in arr:
    if temp % 2 == 0:
        print(temp, end=' ')

[ 6 12 13  9 10 12  6 16  1 17]


- boolean mask: 원본 ndarray와 shpae이 같지만 그 요소값이 모두 boolean으로 구성된 ndarray를 지칭
- 이러한 boolean mask를 이용하여 indexingㅘ는 것이 boolean indexing

In [23]:
print(arr % 2 == 0)

[ True  True False False  True  True  True  True False False]


In [24]:
print(arr[arr % 2 == 0])

[ 6 12 10 12  6 16]


- fancy indexing
- ndarray에 index배열(일반적으로 list)을 전달하여 배열요소는 참조하는 방식
- 연속적이지 않은 요소를 가져오는 방법

In [26]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr[[1,3,4]])

[1 2 3 4 5]
[2 4 5]


In [29]:
arr = np.arange(0,12,1).reshape(3,4).copy()
# 행부터 채워감
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
print(arr[2,2])
print(arr[1:2,2])
print(arr[1:2,1:2])
print(arr[[0,2],2])
print(arr[[0,2],2:3])

# 다차원에서 fancy indexing이 안됨
print(arr[[0,2],[0,2]])
# 이런 경우를 위해 numpy가 함수를 제공 np.ix_()
print(arr[[0,2],[0,2]])

10
[6]
[[5]]
[ 2 10]
[[ 2]
 [10]]
[ 0 10]


- ndarray에 대한 연산

In [38]:
arr1 = np.array([[1,2,3], 
                 [4,5,6]])
arr2 = np.arange(10,16,1).reshape(2,3).copy()
arr3 = np.arange(10,16,1).reshape(3,2).copy()

- ndarray의 연산의 기본은 같은 위치에 있는 원소끼리 연산
- shape가 다르면 연산이 수행되지 않는다

In [39]:
# 행렬합 연산
print(arr1 + arr2)

[[11 13 15]
 [17 19 21]]


In [42]:
# shape가 맞지 않아 연산이 불가능
print(arr1 + arr3)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [45]:
# 행렬곱 연산
print(np.matmul(arr1, arr3))
print(arr1@arr3)

[[ 76  82]
 [184 199]]
[[ 76  82]
 [184 199]]


- 같은 shape을 가지는 ndarray끼리만 4칙연산이 가능한가?
- numpy는 다른 shape을 가지는 ndarray를 이용하여 4칙연산이 가능하도록 broadcating을 지원
- 가능한 경우에만 형태를 변경하여 연산을 진행
- 행렬 곱에는 적용안됨

In [51]:
#(2,3)
arr1 = np.array([[1,2,3], 
                 [4,5,6]])
# (3,)
arr2 = np.array([7,8,9])
print(arr1)
print(arr2)
# 이론상 연산이 불가능하지만 broadcating되어 arr2가 [[7 8 9] [7 8 9]]로 변경
print(arr1 + arr2)

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[ 8 10 12]
 [11 13 15]]


In [50]:
# broadcating되어 10이 [[10 10 10] [10 10 10]]로 변경
print(arr1 + 10)

[[11 12 13]
 [14 15 16]]


- 전지행렬 & iterator(반복자) - for문보다 더 쉽게 반복할 수 있다
- 0차원 => 하나의 숫자 : scalar ex) 5
- 1차원 => 열로 구성 : ㅍㄷㅊ색 ex) [1 2 3 4 5]
- 2차원 => 행과 열로 구성 : matrix ex) [[1 2] [3 4]]
- 3차원 => array라는 표현

- 전치행렬 : 행은 열로, 열을 행으로 바꾼 matrix
- 이렇게 만는 전치행렬(transpose)는 view
- 수학적으로 전치행렬을 표현할때 위첨자로 T를 이용

In [55]:
arr = np.array([[1,2,3], 
                [4,5,6]])
print(arr)
# 전치 행렬을 수할때 T 속성을 이용
print(arr.T)

# 1차원 vector에 대한 전치행렬은 구할 수 없다

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


- iterator(반복자)
- 반복문은 일반적으로 for문과 while문을 사용
- 반복하는 횟수를 알고있는 경우 for
- 조건에 따라 반복할때는 while
- numpy ndarray를 반복처리할 때는 일반적으로 for

In [59]:
# 1차원 numpy ndarray에 대한 요소를 출력
arr = np.array([1,2,3,4,5])

# for문을 이용한 반복처리
for tmp in arr:
    print(tmp, end=' ')

print()
# while문과 iterator를 이용한 반복처리
# 1. 반복자 추출, flags: 인덱스를 사용할때 어떤 방식으로 사용할 것인지
# iterator는 지시자, 포인터 정도로 생각하면 됨
it = np.nditer(arr, flags=['c_index'])
while not it.finished:
    # c 스타일의 인덱스이므로 0부터 시작
    idx = it.index
    print(arr[idx], end=' ')
    # 화살표 옮기는 작업
    it.iternext()

1 2 3 4 5 
1 2 3 4 5 

In [60]:
# 2차원 matrix에 대해서 각 요소를 출력하기
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [63]:
# for문을 이용한 반복처리
for tmp1 in range(arr.shape[0]):
    for tmp2 in range(arr.shape[1]):
        print(arr[tmp1,tmp2], end=' ')

1 2 3 4 5 6 

In [69]:
print(arr)

# itterator을 이용한 반복처리
it = np.nditer(arr, flags=['multi_index'])
while not it.finished:
    # 튜플형태의 인덱스를 가져온다
    idx = it.multi_index
    # fancy indexing 형태
    print(arr[idx], end=' ')
    it.iternext()

[[1 2 3]
 [4 5 6]]
1 2 3 4 5 6 

- iterator를 이용하면 동일한 코드를 사용하여 다양한 차수의 ndarray를 flags만 바꾸면 접근할 수 있다
---

- numpy ndarray의 비교연산
- 사칙연산과 유사하게 동작

In [85]:
np.random.seed(4)
arr1 = np.random.randint(0,10,(2,3))
arr2 = np.random.randint(0,10,(2,3))
print(arr1)
print(arr2)
# boolean mask
print(arr1 == arr2)
print(arr1 > arr2)
print(arr1 < arr2)

[[7 5 1]
 [8 7 8]]
[[2 9 7]
 [7 7 9]]
[[False False False]
 [False  True False]]
[[ True False False]
 [ True False False]]
[[False  True  True]
 [False False  True]]


In [82]:
arr1 = np.arange(10)
arr2 = np.arange(10)
print(np.array_equal(arr1,arr2))

True


- 집계함수와 axis
- 집계함수 : 합, 평균, 표준편차, 분산
- 수학함수 : 최대, 최소, 재곱근, 제곱값, 로그값

In [93]:
arr = np.arange(1,7).reshape(2,3).copy()
print(arr)
print(np.sum(arr))
print(arr.sum())
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
# 최대값의 index 리턴
print(np.argmax(arr))
# 최소값의 index 리턴
print(np.argmin(arr))
# 표준편차
print(np.std(arr))
# 제곱근
print(np.sqrt(arr))

[[1 2 3]
 [4 5 6]]
21
21
3.5
6
1
5
0
1.707825127659933
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


- axis 개념
- numpy의 모든 집계함수는 기본적으로 axis를 기준으로 계싼
- axis를 지정하지 않으면 axis는 none으로 설정 - 대상범위가 배열 전체로 지정

In [98]:
# aixs는 축을 의미하고 이 축을 숫자로 표현(0,1,2...)

# 1차원에서 aixs는 축이 하나고 axis값은 0, 열방향
arr = np.array([1,2,3,4,5])

print(arr.sum(axis=0))
# 1차원에서 axis 1은 존재하지 않으므로 에러
print(arr.sum(axis=1))

15


AxisError: axis 1 is out of bounds for array of dimension 1

- 1차원이면 axis는 0 1개
    - 0 => 열방향
- 2차원이면 axis는 0,1 총 2개
    - 0 => 행뱡향, 1 => 열방향
- 3차원이면 axis는 0,1,2 총 3개 사용할 수 있다
    - 0 => 면, 1 => 행방향, 3 => 열방향

- **차원이 바꾸면 축이 의미하는 것이 바뀐다**

In [112]:
np.random.seed(1)
arr = np.random.randint(0,12,(4,3))
print(arr)
# axis 명시 x, sum()의 대상은 전체 ndarray
print(arr.sum())
# axis 0 => 행방향, sum()의 대상은 ndarray의 열방향
print(arr.sum(axis=0))
# axis 1 => 열방향, sum()의 대상은 ndarray의 행방향
print(arr.sum(axis=1))
# axis 0 => 행방향의 값중 가장 큰값의 index
print(arr.argmax(axis=0))
# axis 1 => 열방향의 값중 가장 큰값의 index
print(arr.argmax(axis=1))

[[ 5 11  8]
 [ 9 11  5]
 [ 0  0  1]
 [ 7  6  9]]
72
[21 28 23]
[24 25  1 22]
[1 0 3]
[1 1 2 2]


- 집계함수를 사용하지 않아도 되지만 속도차이가 많이 난다

In [118]:
arr = np.arange(1,17).reshape(4,4).copy()
print(len(arr[arr>10]))
# False는 0 True는 1, 10이 broadcasting되어 비교연산
print((arr > 10).sum())

6
6


- 정렬

- numpy가 제공하는 정렬함수
- np.sort() : 인자로 들어가는 원본 ndarray는 변화가 없고 정렬된 array를 리턴
- array.sort() : 원본 배열을 정렬하고 리턴이 없다

In [121]:
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[8 3 5 9 0 6 1 7 4 2]


In [122]:
# 원본은 정렬안됨
print(np.sort(arr))
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[8 3 5 9 0 6 1 7 4 2]


In [123]:
# 원본을 정렬시키고 리턴이 없다
print(arr.sort())
print(arr)

None
[0 1 2 3 4 5 6 7 8 9]


- 특수한 슬라이싱을 이용하면 역순으로 정렬할 수 있다

In [126]:
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)
# 내림차순 정렬
print(np.sort(arr)[::-1])

[2 7 4 0 9 8 1 5 6 3]
[9 8 7 6 5 4 3 2 1 0]


- 2차원 데이터에 대한 정렬은 추천되지 않음
---

- numpy array의 병합

In [131]:
arr1 = np.arange(1,7).reshape(2,3).copy()
arr2 = np.arange(7,10)
result1 = np.concatenate((arr1, arr2.reshape(1,3)), axis=0)
print(result1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [133]:
col = np.array([7,8,9,10])
result2 = np.concatenate((arr1, col.reshape(2,-1)), axis=1)
print(result2)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


- Numpy의 delete()
- delete()도 axis를 기준으로 삭제가 진행
- 만약 axis를 명시하지 않으면 자동으로 1차 배열로 변환된 후 삭제

In [137]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)
# 인덱스를 기준으로 지우기
result = np.delete(arr, 1)
print(result)

[[1 2 3]
 [4 5 6]]
[1 3 4 5 6]


In [138]:
# 특정 행 지우기
result = np.delete(arr, 1, axis = 0)
print(result)

[[1 2 3]]


In [139]:
# 특정 열 지우기
result = np.delete(arr, 1, axis = 1)
print(result)

[[1 3]
 [4 6]]


- axis을 -1으로 지정하면 존재하는 axis중 마지막 axis를 지칭한다